### ISSUE TITLE
Bug: Friday is Better

### ISSUE THREAD

**Issue by itsmingjie** [MatthewStanciu/thursday-slack-bot#1]
![image](https://user-images.githubusercontent.com/13333578/85781918-33780300-b6f4-11ea-862e-6179b993f2d7.png)

**Comment by MatthewStanciu** [comment]
WROGN!!!!!!!!!!!!!!!!

**Comment by MatthewStanciu** [comment]
proof https://theoutline.com/post/7807/thursday-is-the-best-day?zd=1&zi=l4jc4bz7
